### ISSUE TITLE
Add trade, farm crop data, and research

### ISSUE THREAD

**Issue by VladMasarik** [David-Melo/captain-of-data#1]
Hi @David-Melo I would like to expand wiki with quick trades, contract trades, research technologies, and farm crops eg. how much water, time and fertility each crop takes. I tried to get the data, but I am very much not as good as you :D I got lost in the code pretty quickly. Is there any chance you could extract them as well?

Sigkill on the discord said that they saw the trades in `Mafi.Base.Prototypes.World.WorldMapEntitiesData` if that help by any chance.

Many thanks!

**Comment by David-Melo** [comment]
Hello!, Sorry for the late reply. Had not seen this and just noticed the post on the discord. I will take a look. In the meantime, have you taken a look at the short comments/summary In the mod file? [DataExtractor.cs](https://github.com/David-Melo/captain-of-data/blob/main/mod/src/DataExtractor.cs)

I'm looking in the farm crops first. The other topics would take some time, if you are interested, I can make a quick guide on my process if you would like to contribute on tackling some of the other things you mentioned.

If interested, let me know and I'll make the guide. The process is basically, trial and error. Using visual studio to build the mod and then starting new games to see the debug data on the log files. So in preparation you would need Visual Studio and a mod environment setup. I know there is an official github repo with a sample mod. If you can get that sample mod workflow going, it would just be a simple and pasting in the mod here and building.

**Comment by VladMasarik** [comment]
Hi, no worries! Any help is great.

> have you taken a look at the short comments/summary In the mod file?
yes, I was surprised by the nice description, although I don't think I fully understood it, as I am missing some context, but that should not be a problem later on.

> I can make a quick guide on my process if you would like to contribute on tackling some of the other things you mentioned.
This would be awesome, especially for the rest of the people wanting to get their own things out of the code. In my case though, I am using linux only so I dont have access to windows. I was only able to partially decompile the code, and see what is inside. I do believe cross compilation of DLL files on linux for windows is possible, but I imagine wonky. Either way, I have yet to properly try it, and actually build the project with VS Code, or do some Wine emulation of VS as I think VS is only for windows.

What are you using the built-in VS decompiler? I have tried the ILSpy, but there were cases where I couldn't really read the code.

**Comment by David-Melo** [comment]
@VladMasarik Updated the repo with research and contracts data. Seems someone else on the wiki started working with contracts and wanted an update

**Comment by VladMasarik** [comment]
Closing as of right now, some blessed soul added all of the information I was looking for on the wiki. Still many thanks for the incredible repo @David-Melo !
