### ISSUE TITLE
Contract Trades

### ISSUE THREAD

**Issue by David-Melo** [David-Melo/captain-of-data#5]

**Comment by L32GIT** [comment]
I've seen you've got a guide in the repo on extraction, but I'm uneducated on Unity or C#, so can't help you with the export.
But I'm interested in linking the data to the Wiki once it's provided.
I'm already in progress of making templatable contracts WikiTable there, you can look at my contributions (https://wiki.captain-of-industry.com/User:L32). Right now data is input manually into templates.
